name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: ilammy/msvc-dev-cmd@v1.0.0
    - name:  Enable Developer Command Prompt
      run: nuget.exe restore cppHowToProgram.sln
           MSBuild.exe /p:Configuration=Debug cppHowToProgram.sln 
