name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Enable Developer Command Prompt
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Nuget restore
      run: MSBuild.exe -t:Restore cppHowToProgram.sln

    - name: Build
      run: MSBuild.exe -t:Build /m -p:Configuration=Debug -p:Platform=x64 cppHowToProgram.sln

    - name: Test
      run: x64\Debug\Tests.exe
