name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: ilammy/msvc-dev-cmd@v1.0.0
    - name:  Enable Developer Command Prompt
      run: MSBuild.exe -t:Build -p:Configuration=Debug -p:Platform=x64 cppHowToProgram.sln
